### ISSUE TITLE
Update code according to React 15.5

### ISSUE THREAD

**Issue by HedgeHogBy** [ayrton/react-key-handler#104]
Hello, Ayrton!

As you most likely know, React was updated to 15.5 and React.PropTypes and React.createClass were extracted into their own packages. So now React shows warning in case you use PropTypes in the old way.
[Here](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html) you can find details.

I made a small pull request #103 to fix this.  It would be great if you could find a time to check and merge it and release a new version with React 15.5 support.

**Comment by ayrton** [comment]
@HedgeHogBy I'll see if I can find the time to look at your PR this weekend. Thanks for your contribution :)

**Comment by HedgeHogBy** [comment]
@ayrton Great! Thank you!

**Comment by silviopaganini** [comment]
any updates on this? would be great to see this update ! thanks !

**Comment by mikecx** [comment]
Looking for this as well, trying to get fully ready for React 16!

**Comment by ayrton** [comment]
Can someone verify the PR is 100% what we need? What about backwards compatibility etc

**Comment by ayrton** [comment]
Fixed in [v1.0.0](https://github.com/ayrton/react-key-handler/blob/master/CHANGELOG.md#100---2017-08-28)
