### ISSUE TITLE
getting error while running  unit test in existing project

### ISSUE THREAD

**Issue by shabanraza** [ayrton/react-key-handler#142]
![screen shot 2017-12-19 at 2 51 39 pm](https://user-images.githubusercontent.com/13848940/34149770-272291b2-e4cc-11e7-88ed-9dda307c9efd.png)

**Comment by shabanraza** [comment]
code is working fine but test cases seems to failing

**Comment by gforge** [comment]
All tests pass in the updated PR: https://github.com/ayrton/react-key-handler/pull/147
