### ISSUE TITLE
Firefox keypress == 0 - amend with which

### ISSUE THREAD

**Issue by gforge** [ayrton/react-key-handler#145]
While keyCode together with keepress returns 0 in Firefox (https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode). This can be mitigated to using a fallback thgrough the `event.which` argument:
```
if (!isNullOrUndefined(keyCode)) {
  // Firefox handles keyCode through which 
  const code = event.keyCode || event.which;
  return keyCode === code;
}

Although the change should probably be towards just `.code`: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

```

**Comment by ayrton** [comment]
Can you open a PR please

**Comment by gforge** [comment]
Already did https://github.com/ayrton/react-key-handler/pull/146

Not sure why it didn't link
