### ISSUE TITLE
组件状态更新，键盘事件无效！

### ISSUE THREAD

**Issue by liujiashun818** [ayrton/react-key-handler#152]
组件状态更新，键盘事件无效！
Component status update, keyboard event invalid!

**Comment by liujiashun818** [comment]
<KeyHandler keyCode={40} onKeyHandle={this.changeImg.bind(this, 'next')}/>
antd中使用这个快捷键有冲突
`<RadioGroup name="radiogroup" defaultValue={1}>
      <Radio value={1}>A</Radio>
      <Radio value={2}>B</Radio>
      <Radio value={3}>C</Radio>
      <Radio value={4}>D</Radio>
    </RadioGroup>`

**Comment by ayrton** [comment]
I'm sorry I don't quite understand what this issue is about. I'm going to close it for now, feel free to explain in English and I'll take a look again
